# サンプルファイルを作成

# 開発中はRUNは重ねてビルド時のレイヤはキャッシュを使うようにする。
# 最終的には綺麗にまとめる

# COPYは単にコピーしたい時に使用
# ADDはtarなどの圧縮ファイルをコピーする時に使う（コピー時に自動で解凍される）

FROM ubuntu:latest
ENV key1 value
ENV key2=value
ENV key3="v a l u e" key4=v\ a\ l\ u\ e
ENV key5 v a l u e
ENV key6 k¥ hey